# Generated by Django 5.2 on 2025-05-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('CONDUCTEUR', 'Conducteur'), ('GESTIONNAIRE', 'Gestionnaire'), ('ADMIN', 'Admin')], default='CONDUCTEUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_validite_permis',
            field=models.DateField(blank=True),
        ),
    ]
