# Generated by Django 5.2 on 2025-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0002_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_validite_permis',
            field=models.DateField(null=True),
        ),
    ]
