# Generated by Django 5.2 on 2025-05-11 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0003_alter_utilisateur_date_validite_permis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('date_achat', models.DateField()),
                ('kilometrage', models.PositiveIntegerField()),
                ('type_carburant', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='vehicules_images')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MAINTENANCE', 'En maintenance'), ('UTILISATION', "En cours d'utilisation")], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(default='users_profiles/user.jpg', upload_to='users_profiles'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_permis',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('kilometrage_parcouru', models.PositiveIntegerField()),
                ('consommation_carburant', models.FloatField(help_text='Consommation en litres')),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_automobile_app.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type_maintenance', models.CharField(max_length=100)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_automobile_app.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('CARBURANT', 'Carburant'), ('MAINTENANCE', 'Maintenance'), ('ASSURANCE', 'Assurance'), ('PEAGE', 'Péage')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_automobile_app.vehicule')),
            ],
        ),
    ]
