# Generated by Django 5.2 on 2025-05-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0004_vehicule_alter_utilisateur_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'DISPONIBLE'), ('En maintenance', 'EN_MAINTENANCE'), ("En cours d'utilisation", 'UTILISATION')], default='DISPONIBLE', max_length=50),
        ),
    ]
