# Generated by Django 5.2 on 2025-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0006_utilisateur_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
