# Generated by Django 5.2 on 2025-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0007_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('TRPTRONIC', 'Triptonic'), ('MANUAL', 'Manual')], max_length=50, null=True),
        ),
    ]
