# Generated by Django 5.2 on 2025-05-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0008_vehicule_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'AUTOMATIC'), ('Triptronic', 'TRIPTRONIC'), ('Manual', 'MANUAL')], max_length=50, null=True),
        ),
    ]
