# Generated by Django 5.2 on 2025-05-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0009_alter_vehicule_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('Van', 'Van'), ('Truck', 'Truck'), ('MVP', 'MVP'), ('SUV', 'SUV'), ('Double Cabin', 'Double Cabin'), ('Wagon', 'Wagon'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Sport', 'Sport')], null=True),
        ),
    ]
