# Generated by Django 5.2 on 2025-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0010_vehicule_color_vehicule_type_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='canDrive',
            field=models.BooleanField(null=True),
        ),
    ]
