# Generated by Django 5.2 on 2025-06-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0011_utilisateur_candrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='canDrive',
            field=models.BooleanField(default=True),
        ),
    ]
