# Generated by Django 5.2 on 2025-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_automobile_app', '0012_alter_utilisateur_candrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='when',
            field=models.DateField(),
        ),
    ]
